package fatec.poo.view;


import fatec.poo.view.GUICadastroVendedor;
import fatec.poo.view.GUICadastroProduto;
import fatec.poo.view.GUICadastroCliente;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCadastroItem1 = new javax.swing.JMenuItem();
        jMenuCadastroItem2 = new javax.swing.JMenuItem();
        jMenuCadastroItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuCadastroItem4 = new javax.swing.JMenuItem();
        jMenuPedido = new javax.swing.JMenu();
        jMenuIPedidotem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Vendas");

        jMenuCadastro.setText("Cadastro");

        jMenuCadastroItem1.setText("Clientes");
        jMenuCadastroItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroItem1ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastroItem1);

        jMenuCadastroItem2.setText("Vendedores");
        jMenuCadastroItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroItem2ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastroItem2);

        jMenuCadastroItem3.setText("Produtos");
        jMenuCadastroItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroItem3ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastroItem3);
        jMenuCadastro.add(jSeparator1);

        jMenuCadastroItem4.setText("Sair");
        jMenuCadastroItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroItem4ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastroItem4);

        jMenuBar1.add(jMenuCadastro);

        jMenuPedido.setText("Pedido");

        jMenuIPedidotem1.setText("Emitir pedido");
        jMenuPedido.add(jMenuIPedidotem1);

        jMenuBar1.add(jMenuPedido);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroItem1ActionPerformed
       new GUICadastroCliente().setVisible(true);
    }//GEN-LAST:event_jMenuCadastroItem1ActionPerformed

    private void jMenuCadastroItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroItem2ActionPerformed
       new GUICadastroVendedor().setVisible(true);
    }//GEN-LAST:event_jMenuCadastroItem2ActionPerformed

    private void jMenuCadastroItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroItem3ActionPerformed
       new GUICadastroProduto().setVisible(true);
    }//GEN-LAST:event_jMenuCadastroItem3ActionPerformed

    private void jMenuCadastroItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroItem4ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuCadastroItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuCadastroItem1;
    private javax.swing.JMenuItem jMenuCadastroItem2;
    private javax.swing.JMenuItem jMenuCadastroItem3;
    private javax.swing.JMenuItem jMenuCadastroItem4;
    private javax.swing.JMenuItem jMenuIPedidotem1;
    private javax.swing.JMenu jMenuPedido;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
